In [51]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt # we'll need this later
import scipy.io as sio

In [52]:
dataset = sio.loadmat("motions10fps.mat")

In [53]:
dataset["allData"][0,0][:,1].shape[0] # video 1, user 1, Y ----- i = video#, j = user ID, k = different angle
#dataset["allData"][0, 0][0,:].shape[0]
print(dataset["allData"].shape[0])
print(dataset["allData"].shape[1])
print(dataset["allData"][0, 0][:,:].shape[0])
print(dataset["allData"][0, 3].shape[1])
print(dataset["allData"][0, 0][0:2,1])
a = np.array([])
a = np.hstack((a, dataset["allData"][0, 0][0:2,1]))
a = np.vstack((a, dataset["allData"][0, 0][0:2,1]))
print(a)
b = np.array([])
b.shape[0]

16
154
299
0
[2.00833292 2.84167129]
[[2.00833292 2.84167129]
 [2.00833292 2.84167129]]


0

In [84]:
window_length = 2
X = np.array([])
X_output = np.array([])
Y = np.array([])
Y_output = np.array([])
Z = np.array([])
Z_output =np.array([])
for i in range(1):#(dataset["allData"].shape[0]): #16
    for j in range(1):#(dataset["allData"].shape[1]): #154
        if dataset["allData"][i, j].shape[1] !=0: # not empty
            for k in range(dataset["allData"][i, j][0,:].shape[0]): #4 
                    for l in range(dataset["allData"][i, j][:,:].shape[0]): #299
                        m = 0
                        p = 0
                        q = 0
                        if k == 1: 
                            while m+window_length  <= dataset["allData"][i, j][:,:].shape[0] - 1:
                                if Y.shape[0] == 0:
                                    Y = np.hstack((Y, dataset["allData"][i, j][m:m+window_length,1]))
                                    Y_output = np.hstack((Y_output, dataset["allData"][i, j][m+window_length,1]))
                                else:
                                    Y = np.vstack((Y, dataset["allData"][i, j][m:m+window_length,1]))
                                    Y_output = np.vstack((Y_output, dataset["allData"][i, j][m+window_length,1]))
                                m = m + 1
                        if k == 2:
                            while p+window_length  <= dataset["allData"][i, j][:,:].shape[0] - 1:  
                                if X.shape[0] == 0:
                                    X = np.hstack((X, dataset["allData"][i, j][p:p+window_length,2]))
                                    X_output = np.hstack((X_output, dataset["allData"][i, j][p+window_length,2]))
                                else:
                                    X = np.vstack((X, dataset["allData"][i, j][p:p+window_length,2])) 
                                    X_output = np.vstack((X_output, dataset["allData"][i, j][p+window_length,2]))
                                p = p + 1
                        if k == 3:
                            while q+window_length  <= dataset["allData"][i, j][:,:].shape[0] - 1: 
                                if Z.shape[0] == 0:
                                    Z = np.hstack((Z, dataset["allData"][i, j][q:q+window_length,3]))
                                    Z_output = np.hstack((Z_output, dataset["allData"][i, j][q+window_length,3]))
                                else:
                                    Z = np.vstack((Z, dataset["allData"][i, j][q:q+window_length,3])) 
                                    Z_output = np.vstack((Z_output, dataset["allData"][i, j][q+window_length,3]))
                                q = q + 1
        print(i, j) # i--video ID, j--user ID

0 0


In [89]:
print(Y)
print(Y_output)

[[ 2.00833292  2.84167129  3.6750039 ]
 [ 2.84167129  3.6750039   4.        ]
 [ 3.6750039   4.          4.        ]
 ...
 [ 9.59996588 11.26663225 12.93334555]
 [11.26663225 12.93334555 12.19999513]
 [12.93334555 12.19999513 12.63333648]]
[[ 4.        ]
 [ 4.        ]
 [ 3.72034349]
 ...
 [12.19999513]
 [12.63333648]
 [13.        ]]
